// <auto-generated />
using System;
using System.Text.Json;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RadioPlaysTracker.Infrastructure.Data;

#nullable disable

namespace RadioPlaysTracker.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RadioPlaysTracker.Core.Models.Album", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("image_url");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("ReleaseDate")
                        .HasColumnType("date")
                        .HasColumnName("release_date");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .HasDatabaseName("idx_albums_name");

                    b.HasIndex("ReleaseDate")
                        .HasDatabaseName("idx_albums_release_date");

                    b.ToTable("albums", (string)null);
                });

            modelBuilder.Entity("RadioPlaysTracker.Core.Models.AlbumArtist", b =>
                {
                    b.Property<string>("AlbumId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("album_id");

                    b.Property<string>("ArtistId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("artist_id");

                    b.Property<int>("ArtistOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("artist_order");

                    b.HasKey("AlbumId", "ArtistId");

                    b.HasIndex("AlbumId")
                        .HasDatabaseName("idx_album_artists_album_id");

                    b.HasIndex("ArtistId")
                        .HasDatabaseName("idx_album_artists_artist_id");

                    b.ToTable("album_artists", (string)null);
                });

            modelBuilder.Entity("RadioPlaysTracker.Core.Models.Artist", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("image_url");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .HasDatabaseName("idx_artists_name");

                    b.ToTable("artists", (string)null);
                });

            modelBuilder.Entity("RadioPlaysTracker.Core.Models.Play", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("PlayedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("played_at");

                    b.Property<string>("SongId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("song_id");

                    b.Property<int>("StationId")
                        .HasColumnType("integer")
                        .HasColumnName("station_id");

                    b.HasKey("Id");

                    b.HasIndex("PlayedAt")
                        .IsDescending()
                        .HasDatabaseName("idx_plays_played_at");

                    b.HasIndex("SongId")
                        .HasDatabaseName("idx_plays_song_id");

                    b.HasIndex("StationId")
                        .HasDatabaseName("idx_plays_station_id");

                    b.HasIndex("StationId", "PlayedAt")
                        .IsDescending()
                        .HasDatabaseName("idx_plays_station_played_at");

                    b.HasIndex("SongId", "StationId", "PlayedAt")
                        .IsUnique()
                        .HasDatabaseName("unique_play");

                    b.ToTable("plays", (string)null);
                });

            modelBuilder.Entity("RadioPlaysTracker.Core.Models.Song", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("id");

                    b.Property<string>("AlbumId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("album_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("DurationMs")
                        .HasColumnType("integer")
                        .HasColumnName("duration_ms");

                    b.Property<JsonDocument>("ExternalLinks")
                        .HasColumnType("jsonb")
                        .HasColumnName("external_links");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("image_url");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("name");

                    b.Property<int>("Popularity")
                        .HasColumnType("integer")
                        .HasColumnName("popularity");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("AlbumId")
                        .HasDatabaseName("idx_songs_album_id");

                    b.HasIndex("Name")
                        .HasDatabaseName("idx_songs_name");

                    b.HasIndex("Popularity")
                        .IsDescending()
                        .HasDatabaseName("idx_songs_popularity");

                    b.ToTable("songs", (string)null);
                });

            modelBuilder.Entity("RadioPlaysTracker.Core.Models.SongArtist", b =>
                {
                    b.Property<string>("SongId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("song_id");

                    b.Property<string>("ArtistId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("artist_id");

                    b.Property<int>("ArtistOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("artist_order");

                    b.HasKey("SongId", "ArtistId");

                    b.HasIndex("ArtistId")
                        .HasDatabaseName("idx_song_artists_artist_id");

                    b.HasIndex("SongId")
                        .HasDatabaseName("idx_song_artists_song_id");

                    b.ToTable("song_artists", (string)null);
                });

            modelBuilder.Entity("RadioPlaysTracker.Core.Models.Station", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("display_name");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("stations", (string)null);
                });

            modelBuilder.Entity("RadioPlaysTracker.Core.Models.AlbumArtist", b =>
                {
                    b.HasOne("RadioPlaysTracker.Core.Models.Album", "Album")
                        .WithMany("AlbumArtists")
                        .HasForeignKey("AlbumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RadioPlaysTracker.Core.Models.Artist", "Artist")
                        .WithMany("AlbumArtists")
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Album");

                    b.Navigation("Artist");
                });

            modelBuilder.Entity("RadioPlaysTracker.Core.Models.Play", b =>
                {
                    b.HasOne("RadioPlaysTracker.Core.Models.Song", "Song")
                        .WithMany("Plays")
                        .HasForeignKey("SongId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RadioPlaysTracker.Core.Models.Station", "Station")
                        .WithMany("Plays")
                        .HasForeignKey("StationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Song");

                    b.Navigation("Station");
                });

            modelBuilder.Entity("RadioPlaysTracker.Core.Models.Song", b =>
                {
                    b.HasOne("RadioPlaysTracker.Core.Models.Album", "Album")
                        .WithMany("Songs")
                        .HasForeignKey("AlbumId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Album");
                });

            modelBuilder.Entity("RadioPlaysTracker.Core.Models.SongArtist", b =>
                {
                    b.HasOne("RadioPlaysTracker.Core.Models.Artist", "Artist")
                        .WithMany("SongArtists")
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RadioPlaysTracker.Core.Models.Song", "Song")
                        .WithMany("SongArtists")
                        .HasForeignKey("SongId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artist");

                    b.Navigation("Song");
                });

            modelBuilder.Entity("RadioPlaysTracker.Core.Models.Album", b =>
                {
                    b.Navigation("AlbumArtists");

                    b.Navigation("Songs");
                });

            modelBuilder.Entity("RadioPlaysTracker.Core.Models.Artist", b =>
                {
                    b.Navigation("AlbumArtists");

                    b.Navigation("SongArtists");
                });

            modelBuilder.Entity("RadioPlaysTracker.Core.Models.Song", b =>
                {
                    b.Navigation("Plays");

                    b.Navigation("SongArtists");
                });

            modelBuilder.Entity("RadioPlaysTracker.Core.Models.Station", b =>
                {
                    b.Navigation("Plays");
                });
#pragma warning restore 612, 618
        }
    }
}
